### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by songxing10000** [beforeold/VCPicker#1]
- (void)DarkAnimation{
    __block typeof(self) Self = self;
    [UIView animateWithDuration:1.5f animations:^{
        Self.backgroundView.backgroundColor = [Self.backgroundView.backgroundColor colorWithAlphaComponent:0.6f];
    } completion:^(BOOL finished) {
        [Self HighlightAnimation];
    }];
}
一、__block是block里面改self才用啊，没有改self不用写吧，

二、看代码貌似是想解决循环引用，应该这样写才对吧        
__weak __typeof__(self) weakSelf = self;

三、不是遇到block在里面用self都会产生循环引用， [UIView animateWithD 这个方法里，block持有self，但self不持有这个block，所以不会循环引用

**Comment by beforeold** [comment]
Uh.... Yes, your are totally right. It is not nesseary to use ```__block``` here.
Thanks for your suggestions, I will fix it and update the latest code very soon.

**Comment by songxing10000** [comment]
回复得这么快，还这么屌的英文啊，话说你这东西挺好用的，已经在项目中愉快地使用了

**Comment by beforeold** [comment]
Very glad to hear it helps.
: )  My team is using this little tool.
Using English may help more people.

**Comment by beforeold** [comment]
Since I have updated the code, this issue will be closed.
