### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by shenyuan000** [beforeold/VCPicker#2]
下面是日志
2018-03-23 15:52:46.236908+0800 TestVCPicker2[63310:3876984] [VCPicker exception: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[3]]

是在调用- (void)findAndShowControllers 方法导致的

**Comment by beforeold** [comment]
Fine, i got it.
Since i am very very busy these days, i am not able to fix it very soon.
Anyway i will try my best to update it.
💯

**Comment by shenyuan000** [comment]
ok 问题产生的原因是因为没有传入prefixes数组导致的 “[VCPicker activateWhenDebug];” 
这是控制器数组存储的数据 都是系统的
“<__NSArrayI 0x7fc41a544c30>(
BlkTraceController,
CMKLowDiskSpaceAlertController,
DOCBaseDocumentBrowserViewController,
DOCBrowserViewController,
DOCDocBrowserVC_UIActivityViewController,
DOCDocumentManagerNavigationViewController,
DOCExportModeViewController,
DOCFullDocumentManagerViewController,
DOCFullVC_DOCInfoViewController,
DOCInfoViewController,
DOCLightDocumentManagerViewController,
DOCRemoteViewController,
DOCSnapshotBrowserViewController,
DOCSourceViewController,
DOCTargetSelectionBrowserViewController,
DOCViewServiceErrorViewController,
DevicePINController,
DevicePINSetupController,
DiagnosticDataController,
FLHomeViewController,
GLKViewController,
KeychainSyncAdvancedSecurityCodeController,
KeychainSyncAppleSupportController,
KeychainSyncDevicePINController,
KeychainSyncPhoneNumberController,
KeychainSyncSMSVerificationController,
KeychainSyncSetupController,
MYViewController,
PSAboutHTMLSheetViewController,
PSAboutTextSheetViewController,
PSAccountSecurityController,
PSAccountsClientListController,
PSAppListController,
PSAppleIDSplashViewController,
PSDetailController,
PSDocumentsPolicyController,
PSEditableListController,
PSInternationalController,
PSInternationalLanguageController,
PSInternationalLanguageSetupController,
PSKeyboardNavigationSearchController,
PSKeychainSyncSecurityCodeController,
PSKeychainSyncTextEntryController,
PSKeychainSyncViewController,
PSLargeTextController,
PSLargeTextSliderListController,
PSListController,
PSListItemsController,
PSLocaleController,
PSMagnifyController,
PSRootController,
PSSearchResultsController,
PSSetupController,
PSSharableDetailController,
PSSoftwareUpdateReleaseNotesDetail,
PSSplitViewController,
PSSpotlightSearchResultsController,
PSUISearchController,
PSUIWirelessDataOptionsListController,
PSUsageBundleDetailController,
PSViewController,
PTSChoiceViewController,
PTSImagePickerViewController,
PTSModuleController,
PTSettingsController,
PopBackListItemsController,
ProblemReportingAboutController,
ProblemReportingController,
ViewController,
WKActionSheet,
WKDateTimePopoverViewController,
WKFileUploadPanel,
WKImagePreviewViewController,
WKSelectTableViewController
)”

**Comment by beforeold** [comment]
Got it. Thanks again.

**Comment by beforeold** [comment]
fixed

**Comment by beforeold** [comment]
will not crash in latest version, this issue shall be closed.
